### ISSUE TITLE
Organic Ads

### ISSUE THREAD

**Issue by MikaBrk** [MikaBrk/Celestified#2]
Trebamo krenut radit organic ads na svim mogucim platformama. Sto znaci napravimo account na svakom website ja bi se personalno koncentrirao na Instagram, TikTok, Facebook, YouTube na pocetku. Tamo cemo repostat video i stavljat organic like videos kako bi dobile sta veci view count i kako bi bile suggested by the system.
Svaki od tih accounta treba biti povezan sa stranicom tako da ljudi zapravo imaju di kliknut ako im se proizvod zapravo svidi
ja bi ciljo na 2-4 videa na dan na svakoj platform kaka bi smo boostali account

**Comment by MikaBrk** [comment]
Gabi - instagram I YouTube
Mika - TikTok

**Comment by NanoSleek** [comment]
yt / 2 ada postana
insta / 2 ada postana

dns jos
